name: examen-workflow

on:
  push:
    branches:
        - "nueva-caracteristica"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: Descargar codigo
            uses: actions/checkout@v4

          - name: Configurar python
            uses: actions/setup-python@v6

          - name: Ejecucion test
            run: |
                  pip install pytest
                  pytest test.py

          - name: Docker
            uses: docker/build-push-action@v6
            with:
              context: .
              push: false
